#use_frameworks!


#pre_install do |installer|
#  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
#  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
#end


platform :ios, '9.0'

target 'CommonPay_Example' do
#  pod 'WechatOpenSDK'
  pod 'CommonPay', :path => '../'
  

  target 'CommonPay_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
